version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: ngsoft-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ngsoft
      POSTGRES_PASSWORD: ngsoft_password
      POSTGRES_DB: ngsoft
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ngsoft"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: ngsoft-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://ngsoft:ngsoft_password@postgres:5432/ngsoft?schema=public
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET:-development-secret-change-in-production}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      postgres:
        condition: service_healthy
    command: sh -c "npx prisma generate && npx prisma migrate deploy && npm run dev"

volumes:
  postgres_data:
    driver: local
